### PR TITLE
Document how to build from source

### PR DESCRIPTION
**Pull request by gogo2464**
Tell how to build ysoserial from source using command line. Inspired from the cicd.

### CODE REVIEW

**Comment by irsdl** [comment]
I think adding this without mentioning the Visual Studio compile or using Visual Studio command prompt might imply the need to use a different compilation process. If you have the time to add those too, that would be great.

We also have the following workflow if someone wants to use a github fork to build it:
`https://github.com/pwntester/ysoserial.net/blob/master/.github/workflows/build.yml`

I will wait for @pwntester to comment on this as this is to do with the documentation mainly.

**Comment by gogo2464** [comment]
good idea! I will encourage the install of visual studio from chocolatey for a full cmd line linstall! seems cleaner. even on windows

**Comment by pwntester** [comment]
LGTM, perhaps adding a line about the Action workflow as @irsdl mentioned

**Review by pwntester — APPROVED** [review]

**Comment by gogo2464** [comment]
In my humble opinion, people should have to look at the workflow:
-because of @use in cicd that may be confused
-because it might be considered as "my code api is not documented, read the directly."

If really you need it to merge, I am open.

**Comment by gogo2464** [comment]
is it ready to merge?

**Pull request merged**
